### ISSUE TITLE
Tree view indentation and sort

### ISSUE THREAD

**Issue by MaxCR86** [Soluto/tweek#723] opened 2018-01-15 09:55 UTC
![screen shot 2018-01-15 at 11 50 26](https://user-images.githubusercontent.com/5471450/34936547-81584216-f9ea-11e7-95af-ada6c7c2d130.png)

**Sort**
Folders are usually shown first in a tree list, sorted by ABC. 
After them, show the keys in that parent folder, also sorted by ABC. 
That will allow to better differentiate between nested folders and keys.

**Indentation**
Nested keys which are not folders are indented a bit deeper in than nested folders are. 
This is VERY confusing, and makes you think that the keys are actually nested within the nested folder, rather than reside in the parent folder itself. 
Folders and keys nested in the same folder should have identical indentation - meaning start from the same point (including the folder icon as the starting point!).

Thanks <3
   - Max.

**Comment by Yshayy** [comment] 2018-01-17 09:36
Duplicate of #631

**Closed** 2018-03-01 09:24 UTC
Labels: UX, good first issue, in progress, service/editor
